### ISSUE TITLE
Can't download most recent version because of weird Go versioning rules

### ISSUE THREAD

**Issue by johnnyb** [shuLhan/go-bindata#46]
If you do "go get https://github.com/shuLhan/go-bindata" it downloads 3.4.0, and if you do "https://github.com/shuLhan/go-bindata@3.6.0" it gives an error:

>  "version "v3.6.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3". 

The go.mod file is forcing it to follow newer language conventions, which say that versions beyond v1 require the major version to be part of the import path.  So, to follow the rule, you would need to move your code into a subdirectory v3, so that the import path would be https://github.com/shuLhan/go-bindata/v3.  Information about this is here:

https://blog.golang.org/v2-go-modules

You might try just removing the go.mod file and then releasing 3.6.1, or you could try following the newer convention and moving everything to a v3 folder.  Basically, it looks like they are trying to discourage anyone from doing major versions greater than 1 unless they really, really, really mean it.

**Comment by shuLhan** [comment]
@johnnyb 

Thank you for noticing and raising this issue. The problem is if we move them into subdirectory there would be break other peoples that have not moved to Go module, yet. We need a solution that backward compatible and easily patched (new patch to v3 subdirectory should also update the root, non-module but v3 too, and vice versa). I believe this issue require major code restructuring, I will look into it.

**Comment by shuLhan** [comment]
@johnnyb 

I have remove the go.mod file and release 3.6.1 as you suggested.  For the Go modules, we have /v4 subdirectory which contains the exact copy. Seems like this is the only solution to moving forward.

Thank you for your input.
